export const quizTypes = [
  'General Knowledge',
  'Job Interview',
  'Exam Preparation',
  'Trivia Night',
  'Logical Reasoning',
  'Technical Skills Test',
  'Personality Quiz',
  'Language Learning',
  'History Quiz',
  'Science Pop Quiz',
  'Just for Fun',
  'Vocabulary Test',
  'Math Challenge',
  'Code Debugging',
  'Medical Terminology',
  'Legal Case Study',
  'Creative Writing Prompt',
  'IQ Test',
  'Icebreaker Questions',
  'Other',
];
