export const topics = [
  "CVE (Common Vulnerabilities and Exposures)",
  "Symmetric and Asymmetric Encryption",
  "OWASP Top 10",
  "Purple Team",
  "Zero-Day Attack",
  "Hash Value",
  "SSRF (Server-Side Request Forgery)",
  "CVSS (Common Vulnerability Scoring System)",
  "EDR/XDR (Endpoint/Extended Detection & Response)",
  "DNS Tunneling",
  "Red Team vs Blue Team",
  "Reverse Shell",
  "IPv4 / IPv6",
  "SAAS (Software as a Service)",
  "MITM (Man-in-the-Middle)",
  "OSI Layer",
  "VPN Encryption",
  "Subnetting",
  "Active Directory",
  "Phishing",
  "SIEM (Security Information and Event Management)",
  "AES and DES",
  "IDOR (Insecure Direct Object Reference)",
  "Nmap Stealth Scan",
  "IOT and OT",
  "UID",
  "SEToolkit",
  "Dom-based XSS",
  "Sandboxing",
  "IDS and IPS",
  "Thread Hunting and Threat Detection",
];
